name: Run API Login Tests with Report on Multiple Environments

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * *'  # Runs daily at 15:30 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [DEV, INT, UAT]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17 and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run API Tests on ${{ matrix.environment }}
        env:
          TEST_ENV: ${{ matrix.environment }}
        run: |
          echo "Running tests on environment: $TEST_ENV"
          mvn clean test -Denv=$TEST_ENV

      - name: Upload Surefire Reports (${{ matrix.environment }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.environment }}
          path: target/surefire-reports/

      - name: Upload Allure Results (${{ matrix.environment }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.environment }}
          path: target/allure-results/

      - name: Download and Extract Allure CLI
        run: |
          ALLURE_VERSION=2.27.0
          wget -nv https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.tgz
          tar -xzf allure-commandline-${ALLURE_VERSION}.tgz
          EXTRACTED_DIR=$(tar -tzf allure-commandline-${ALLURE_VERSION}.tgz | head -1 | cut -f1 -d"/")
          mv "$EXTRACTED_DIR" allure

      - name: Add Allure to PATH
        run: echo "${{ github.workspace }}/allure/bin" >> $GITHUB_PATH

      - name: Generate Allure Report (${{ matrix.environment }})
        if: always()
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure HTML Report (${{ matrix.environment }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.environment }}
          path: target/allure-report/

      - name: Copy report to docs folder (${{ matrix.environment }})
        if: always()
        run: |
          rm -rf docs
          cp -r target/allure-report docs

      - name: Deploy to GitHub Pages (${{ matrix.environment }})
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
          publish_branch: gh-pages
          force_orphan: true
          
      - name: Check report exists (${{ matrix.environment }})
        run: ls -R docs
