name: Run API Login Tests with Report

on:
  workflow_dispatch:
  schedule:
    - cron: '25 18 * * *'  # Runs every day at 18:25 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17 and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run API Tests
        run: mvn clean test

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload Allure Results (if available)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/

      - name: Install Allure CLI
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.29.1/allure-2.29.1.zip
          unzip -q allure.zip -d allure
          echo "$(pwd)/allure/allure-2.29.1/bin" >> $GITHUB_PATH

      - name: Generate Allure Report
        if: always()
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report/
