name: Run API Login Tests with Report

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * *'  # Runs every day at 15:30 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17 and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run API Tests
        run: mvn clean test

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload Allure Results (if available)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/

      - name: Download and Extract Allure CLI
        run: |
          ALLURE_VERSION=2.27.0
          wget -nv https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.tgz
          tar -xzf allure-commandline-${ALLURE_VERSION}.tgz

      - name: Add Allure to PATH
        run: echo "$(pwd)/allure-commandline-2.27.0/bin" >> $GITHUB_PATH

      - name: Generate Allure Report
        if: always()
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report/
